import type { Metadata } from "next";
import "./globals.css";
import { archivo, konnect, gilroyMedium, gilroySemi } from "./fonts";
import Favicon from "@/public/favicons/logo.png";
import Footer from "@/components/03_Footer";
import Header from "@/components/00_Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: [{ rel: "icon", url: Favicon.src }],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const fontVars = [
    archivo.variable,
    konnect.variable,
    gilroyMedium.variable,
    gilroySemi.variable,
  ].join(" ");

  return (
    <html lang="en" className={fontVars}>
      <body className="bg-[var(--bg)]">
        <div className="page-shell">
          <Header />
          <main>{children}</main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
